version: "3"

services:
  babelfishpg-1.3.1-amazonlinux-2:
    container_name: babelfishpg-1.3.1-amazonlinux.2
    image: babelfishpg:1.3.1-amazonlinux.2
    ports:
      # Port forwarding not supported by BabelfishPG
      - 1433:1433
      - 5432:15432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - BABELFISH_USER=bbf
      - BABELFISH_PASS=password
      - BABELFISH_DB=bbf
      - BABELFISH_MIGRATION_MODE=multi-db
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - babelfish

networks:
  babelfish:
      